on:
  push:
    branches: main
    paths-ignore:
      -'**/README.md'
      -'LICENSE'
      -'.gitignore'
      -'.github/workflows/push.yml'
name: Push Shiny Dashboard to Shinyapps.io

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      #actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install ubuntu dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with: 
          packages: >- 
            libcurl4-openssl-dev 
            libharfbuzz-dev libfribidi-dev
            libudunits2-dev libgdal-dev
            libpq-dev libgeos-dev
            libproj-dev
          version: 1
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: '4'
          r-version: '4.5.0'
      - name: Install R dependency
        uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"UBCleanDash"'
          cache-version: 2
      - name: Decode secret and save as env file
        run: |
          echo "${{ secrets.ENV_FILE}}" | base64 -d > .Renviron

      - name: run the config file for the push
        run: Rscript --verbose ./config.R
      
